apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: webapi-deployment
  namespace: webapps
spec:
  selector:
    matchLabels:
      app: webapi
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: webapi
          image: us-central1-docker.pkg.dev/project1-444610/jenkins-project/pn1-dotnet-api:5 # Image that will be used to containers in the cluster
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: Always
          ports:
            - containerPort: 5000 # The port that the container is running on in the cluster
