apiVersion: v1
kind: Pod
spec:
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 8.8.8.8
      - 1.1.1.1
  containers:
    - name: maven
      image: maven:3.9.9-eclipse-temurin-17
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /workspace
          name: shared-volume
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
          
    - name: sonar-scanner
      image: sonarsource/sonar-scanner-cli:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /workspace
          name: shared-volume
      resources:
        requests:
          cpu: "250m"
          memory: "500Mi"
        limits:
          cpu: "1"
          memory: "2Gi"
          
    - name: git
      image: alpine/git:latest
      command: ["cat"]
      tty: true
      volumeMounts:
        - mountPath: /workspace
          name: shared-volume
      resources:
        requests:
          cpu: "250m"
          memory: "100Mi"
        limits:
          cpu: "500m"
          memory: "500Mi"     

    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: Always
      command:
        - sleep
      args:
        - "9999999"
      volumeMounts:
        - mountPath: /workspace
          name: shared-volume
        - mountPath: /kaniko/.docker
          name: docker-config
        - mountPath: /kaniko-secret
          name: gcp-credentials
      resources:
        requests:
          cpu: "250m"
          memory: "500Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
  volumes:
    - name: shared-volume
      persistentVolumeClaim:
        claimName: shared-pvc
    - name: docker-config
      emptyDir: {}
    - name: gcp-credentials
      secret:
        secretName: gcp-gar-cred
